spring:
  application:
    name: inno-payment-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:secret@localhost:27017/payment_db?authSource=admin}
      auto-index-creation: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.innowise.*"
        spring.json.use.type.headers: true
    topic:
      order-events: order-events
      payment-events: payment-events

random-api:
  base-url: https://www.randomnumberapi.com
  path: /api/v1.0/random
  min: 100
  max: 1000
  count: 1

server:
  port: 8087


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        '[http.server.requests]': true
  tracing:
    sampling:
      probability: 1.0  
  otlp:
    tracing:
      endpoint: ${TEMPO_ENDPOINT:http://tempo:4318/v1/traces}
  loki:
    url: ${LOKI_URL:http://loki:3100}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true